tracker/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField , PasswordField , EmailField , SubmitField,ValidationError 
from wtforms.validators import DataRequired , Length , Email ,EqualTo

class Register(FlaskForm):    

    def validate_user_name(self , user_name_to_check):
        from tracker.dbmodels import User 
        user = User.query.filter_by(user_name = user_name_to_check.data).first()
        if user :
                raise ValidationError("User name already exists , Please try another one!")
    def validate_email(self , email_to_check):
          from tracker.dbmodels import User
          email = User.query.filter_by(email = email_to_check.data).first()
          if email:
                raise ValidationError("Email adress already exists! Please try a different one ")
    
    user_name = StringField(label='User Name :' , validators = [Length(min=5 , max=15) , DataRequired()])
    email = EmailField(label = 'Email :' , validators = [Length(min=6 , max=25) , Email()])
    password1 = PasswordField(label='Password :' , validators = [Length(min=7) , DataRequired()])
    password2 = PasswordField(label='Confirm Password :', validators = [EqualTo('password1') , DataRequired()])
    submit = SubmitField(label='Create Account')

class Login(FlaskForm):
    
    user_name = StringField(label='Name :' , validators = [Length(min=5 , max=15) , DataRequired()])
    password = PasswordField(label='Password :' , validators = [Length(min=7) , DataRequired()])
    submit = SubmitField(label='Login')
    
class AddCategory(FlaskForm):
    def validate_category_name(self , category_to_check):
        from tracker.dbmodels import Category
        category = Category.query.filter_by(category_name = category_to_check.data).first()
        if category:
             raise ValidationError('Category already exists!')     
    
    category_name = StringField(label='Category' , validators=[DataRequired()])
    submit = SubmitField(label='Add Category') 

class DeleteCategory(FlaskForm):
     ...

tracker/__init__.py
import os
from flask import Flask , current_app
from flask_sqlalchemy import SQLAlchemy 
from sqlalchemy import create_engine
from tracker.routes import bp
from flask_bcrypt import Bcrypt as Bcr
from flask_login import LoginManager , login_user
from dotenv import load_dotenv


db = SQLAlchemy()
bcrypte = Bcr()
login_manager = LoginManager()

load_dotenv(rf'C:\Users\amine\to unpack\WebDev\Expanses-Tracker\.env')

def create_app():
    app = Flask(__name__)
    app.register_blueprint(bp)
    bcrypte.init_app(app)
    login_manager.init_app(app)
    app.config.from_prefixed_env()
    # app.config.from_prefixed_env('SQLALCHEMY')
    # os.getenv('SQLALCHEMY_DATABASE_URI')
    db.init_app(app) 
    return app
"""
This is how To delete data from the database:
with app.app_context():
...     toDel = Category.query.filter_by(category_name = 'Test').first()
...     db.session.delete(toDel)
...     db.session.commit()
"""

tracker/routes.py
from flask import Blueprint , render_template , redirect , url_for ,flash
from tracker.forms import Register , Login
from flask_login import login_user , logout_user , login_required
# from tracker.dbmodels import load_user --> This causes circular import ,so it is imported inside each route/function

bp = Blueprint('routes' , __name__)    
@bp.route('/')
@bp.route('/home')
def home():
    from tracker.dbmodels import load_user
    return render_template("home.html")

@bp.route('/dashboard')
@login_required
def dashboard():
    return render_template("dashboard.html")

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/register',methods = ['GET' , 'POST'])
def register():
    from tracker.dbmodels import User
    from tracker import create_app , db
    app = create_app()
    form = Register() # This allows us to make conditions upon the redirected template 
    # If the submit btn of the form is clciked !
    if form.validate_on_submit():
        user_to_create = User(
            user_name = form.user_name.data,
            email = form.email.data,
            get_password = form.password1.data)
        # Add the entered data from the Form to the Database and save
        with app.app_context():
            db.session.add(user_to_create)
            db.session.commit()
            login_user(user_to_create)
        return redirect(url_for("routes.home"))
    # We need to check if the user entered the data in the correct way as it was mentioned in the validators
    if form.errors:
        for err in form.errors.values():
            flash(f'There was an error with creating the user :{err}' ,category='danger')
    # We need to check if the email or the username entered is unique 
        # And this was done in the forms.py inside the login form class

    return render_template('register.html' , form = form)

@bp.route('/login' , methods = ['GET', 'POST'])
def login():
    # These imports are here to avoid circular imports problem
    from tracker.dbmodels import User 
    from tracker import db , create_app
    app = create_app()
    form = Login()
    if form.validate_on_submit():
        attempted_user = User.query.filter_by(user_name = form.user_name.data).first()
        if attempted_user and attempted_user.check_password(attempted_password=form.password.data):
            login_user(attempted_user)
            flash("You are successfully logged in!",category='success')
            return redirect(url_for('routes.dashboard'))

        else:
            flash('Log in Error',category='danger')
        
        return redirect(url_for("routes.home"))    
    return render_template('login.html' , form = form )

@bp.route('/logout')
def logout():
    logout_user()
    flash("You are currently logged out")
    return render_template('home.html')

@bp.route('/add' , methods = ['GET' , 'POST'])
def add():
    from tracker.dbmodels import Category , Item
    from tracker.forms import AddCategory
    from tracker import create_app , db
    app = create_app()
    form = AddCategory()
    if form.validate_on_submit():
        created_category = Category(category_name = form.category_name.data)
        with app.app_context():
            db.session.add(created_category)
            db.session.commit()
            return redirect(url_for('routes.add'))
    if form.errors:
        for err in form.errors.values():
            flash(err)
    categories = [str(category) for category in  Category.query.all()]
    items =[str(item) for item in  Item.query.all()]
    
    return render_template('categories.html' , form = form , categories = categories , items = items)

tracker/templates/about.html
{%extends 'base.html'%}
{%block content%}
    <div class="">
        <h1>This is the about section</h1>
    </div>
{%endblock content%}

tracker/templates/addXpanses.html
{%extends 'base.html'%}

{%block title%} Add  {%endblock%}

tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Xpanses :{%block title%}{%endblock title%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='./dist/output.css')}}">
    <link rel="stylesheet" href="{{url_for('static' , filename = './style/style.css')}}">
    <script src="https://kit.fontawesome.com/85d4076826.js" crossorigin="anonymous"></script>
    <script src="../static/index.js"></script>

</head>
<body class="bg-body min-h-screen flex flex-col">
    <nav class=" bg-nav p-4">
        <div class="container mx-auto flex items-center justify-between ">
            <div class="logo w-1/3">
                <a class="text-3xl font-semibold  text-link hover:text-button "  href="#">Xpanses</a>
            </div>
            {%if current_user.is_authenticated %}
                <div class="container nav-links flex w-1/3 ">
                    <div class="mx-auto  w-full flex items-center justify-between   ">   
                        <a class=" text-lg     text-link  hover:text-opacity-70" href='{{url_for("routes.home")}}'>Home</a>
                        <a class=" text-lg     text-link  hover:text-opacity-70"  href='{{url_for("routes.add")}}'>Add Expanses</a>
                        <a class=" text-lg     text-link  hover:text-opacity-70"  href='{{url_for("routes.dashboard")}}'>DashBoard</a>
                    </div>
                </div>

                <div class="container account flex justify-evenly items-center w-1/3">
                    <p class="text-button_hover">Welcome {{current_user}}</p>
                    <div class="bg-button_hover py-1 px-4 rounded-md  ">
                        <button class="text-lg font-semibold text-link" >
                        <a href="{{url_for('routes.logout')}}">Logout</a>    
                        </button>
                    </div>
                </div>
            {%else %}
                <div class="container nav-links flex w-3/5 ">
                    <div class="mx-auto  w-full flex items-center justify-evenly   ">   
                        <a class=" text-lg     text-link  hover:text-opacity-70" href='{{url_for("routes.home")}}'>Home</a>
                        <a class=" text-lg     text-link  hover:text-opacity-70"  href='{{url_for("routes.add")}}'>Add Expanses</a>
                        <a class=" text-lg     text-link  hover:text-opacity-70"  href='{{url_for("routes.dashboard")}}'>DashBoard</a>
                    </div>
                </div>    
            
                <div class="container w-1/2">
                    <div class="bg-button py-1 px-4 rounded-md  ml-auto" style="width:5.1rem ;">
                        <button class="text-lg font-semibold text-link" >
                        <a href="{{url_for('routes.login')}}">Login</a>    
                        </button>
                    </div>
                </div>
            
            {%endif%}
        </div>
    </nav>
    <header>
        {%with messages = get_flashed_messages(with_categories = true)%}
            {%if messages%}
                {%for category , message in messages%}
                    <h1>
                        <div class="error-message">
                            {{message}}
                        </div>
                    </h1>
                
                {%endfor%}
            
            {%endif%}
        {%endwith%}

    </header>
    <main class="container  flex-grow">
{%block content%}{%endblock content%}
    </main>
    <!-- bottom-0 left-0 right-0 fixed -->
    <footer class=" bg-nav p-2 h-fit">  
            <div class="first-row container mx-auto flex flex-wrap  items-center justify-center  ">
                <div class="butt p-2 mr-2 text-2xl font-semibold hover:text-button_hover" >
                    <a href='{{url_for("routes.home")}}'> Xpanses </a>
                </div>
                <div class="links text-xl font-semibold  ">
                    <a class="px-4 text-link  hover:text-opacity-40 " href="#">Contact</a>
                    <a class="px-4 text-link  hover:text-opacity-70 " href="#">FAQ</a>
                    <a class="px-4 text-link  hover:text-opacity-70 " href="#">Privacy</a>
                </div>
            </div>
            <div class="second-row container mx-auto flex justify-center   ">
                <a class="px-4" href='https://github.com/Amine-iD/Expanses-Tracker'>
                    <i class="fa-brands fa-github  text-2xl hover:text-link"> </i>
                </a>
                <a class="px-4"  href="https://linkedin.com">
                    <i class="fa-brands fa-linkedin text-2xl hover:text-link"></i>
                </a>
                <a class="px-4" href="https://x.com">
                    <i class="fa-brands fa-x-twitter text-2xl hover:text-link"></i>
                </a>
            </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

tracker/templates/categories.html
{%extends 'base.html'%}
{%block title%} Categories  {%endblock%}
{%block content%}

<div class="container form-container my-10 flex flex-row ">
    <!-- Add a category -->
    <div class="categories-form w-1/2 ">
        <form action="" method="post" class="">
            {{form.csrf_token}}
            <div class="container flex flex-col items-center  ">
                <div class="field-container">
                    {{form.category_name.label()}}
                    {{form.category_name(placeholder = 'ex:Clothing', class = 'input')}}
                </div>
                <div class="field-container">
                    {{form.submit(class = 'btn' , id = 'btn')}}
                </div>
            </div>
        </form>
        
    </div>
    <div class="item-form w-1/2">
        <form action="" method="post" class="">
            {{form.csrf_token}}
            <div class="container flex flex-col items-center  ">
                <div class="field-container">
                    {{form.category_name.label()}}
                    {{form.category_name(placeholder = 'ex:Clothing', class = 'input')}}
                </div>
                <div class="field-container">
                    {{form.submit(class = 'btn' , id = 'btn')}}
                </div>
            </div>
        </form>
    </div>
</div>
<br>
<hr>
<br> <br>
<!-- Add expnses as rows -->
    <div class="container mx-auto px-4 h-2/5">
        <div class="table-btns flex w-full  ">
            <button class=" bg-blue-500  hover:bg-blue-700  text-white font-bold  py-2 px-4 rounded-md" onclick="addRow()">New row</button>
            <button class=" bg-red-500   hover:bg-red-700   text-white font-bold  py-2 px-4 rounded-md mx-2" onclick="deleteRow()" id="deleteBtn">Delete row</button>
            <button class=" bg-green-500 hover:bg-green-700 text-white font-bold  py-2 px-4 rounded-md ml-auto">Save</button>
        </div>
        <h1 class="text-2xl font-bold mb-4 text-center">Purchased Items</h1>
        <div class="overflow-x-auto ">
            <table class=" exp-table min-w-full bg-white border border-gray-200 h-1/2 overflow-y-scroll">
                <thead>
                    <tr class="hover:bg-gray-200" onclick="selectRow()">
                        <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-700">Category</th>
                        <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-700">Item</th>
                        <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-700">Description</th>
                        <th class="py-2 px-4 border-b border-gray-200 bg-gray-100 text-left text-sm font-semibold text-gray-700">Date</th>
                    </tr>
                </thead>
                <tbody id="purchased-items-body">
                    <!-- Rows will be added dynamically by JavaScript -->
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4" class="py-2 px-4 border-t border-gray-200 text-right font-semibold">Total Items</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

<script src="../static/index.js"></script>
<script>
    // VARIABLES
    let items = JSON.stringify({{items | tojson}})
    let categories = JSON.stringify({{categories | tojson}})
    loadData(items , categories)
</script>
{%endblock content%}

tracker/templates/dashboard.html
{%extends 'base.html'%}

{%block title%}Dash-Board{%endblock title%}

{%block content%}
<div class="flex w-full h-screen  mt-2 mx-auto justify-evenly items-center">
    <section class="balance-dashboard w-1/3 h-1/2  mx-auto  text-center border-solid border-2 border-nav rounded-md bg-link ">
        <div class="container h-2/3 font-mono ">
            <div class="text-3xl my-4">Balance</div>
            <div class="text-2xl text-center my-32 ">
                <span>Your Current Balance: </span> 
                <span class="text-right">3000.00 DH</span>
            </div>
        </div>
    </section>

    <section class="spent-dashboard  w-1/3 h-1/2  mx-auto  text-center border-solid border-2 border-nav rounded-md  bg-link">
        <div class="container h-2/3 font-mono  ">
            <div class="text-3xl my-4  ">Spent</div>
        </div>
    </section>
</div>
{%endblock content%}

tracker/templates/home.html
{%extends 'base.html'%}

{%block title%}Home{%endblock title%}

{%block content%}
<h1>This is Home</h1>
<button ><a href="{{url_for('routes.register')}}">Register</a></button>
{%endblock content%}

tracker/templates/login.html
{%extends 'base.html'%}

<head>
    {%block title%} Login {%endblock title%}
    <link rel="stylesheet" href="../style/style.css">
</head>

{%block content%}
    <div class="form-container container my-10  ">
        <form method="post" >
            {{form.csrf_token}}
            <div class="container flex flex-col items-center ">
                    <div class="field-container">
                        {{form.user_name.label()}} <!--the label name is extracted from forms.py in the user_name variable of the Login class-->
                        {{form.user_name(placeholder = 'Enter Your Name:' , class = 'input')}}
                    </div>
                    <br>
                    <div class="field-container">
                        {{form.password.label()}}
                        {{form.password(placeholder = ' Enter Your Password', class = 'input' )}}
                    </div>
                    <br>
                    <div class="field-container">
                        {{form.submit(class = 'btn')}}
                    </div>
                    <div class="form-links">
                        <span>Don't have an account?</span>
                        <span> <a href="{{url_for('routes.register')}}">  Register  </a> </span>
                    </div>
                </div>
        </form>
    </div>
{%endblock content%}

tracker/templates/register.html
{%extends 'base.html'%}
<head>
    {%block title%} Register {%endblock title%}
    <link rel="stylesheet" href="../style/style.css">
</head>
{%block content%}
    <div class="form-container container my-10 ">
        <form method="post" action="" >
                {{form.csrf_token}}
            <div class="container flex flex-col items-center  ">
                <div class="field-container">
                    {{form.user_name.label()}}
                    {{form.user_name( class = 'input')}}
                </div>
                <br>
                
                <div class="field-container">
                    {{form.email.label()}}
                    {{form.email( class = 'input')}}
                </div>
                <br>
                
                <div class="field-container">
                    {{form.password1.label()}}
                    {{form.password1(class = 'input' )}}
                </div>
                <br>
                
                <div class="field-container">
                    {{form.password2.label()}}
                    {{form.password2(class = 'input' )}}
                </div>
                <br>
                
                <div class="field-container">
                {{form.submit( class='btn')}}
                </div>
                <br>
                <div class="form-links">
                    <span> Already have an account?</span>
                    <span> <a href="{{url_for('routes.login')}}"> Login  </a></span>
                </div>      
            </div>
        </form>    

    </div>
{%endblock content%}